const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],P=JSON.parse(localStorage.fw_prefs||'{}'),S={m:P.minutes||3,focus:P.focus??true,keep:P.keep??true,n:P.nudge||6,rem:P.reminder??false,time:P.reviewTime||'20:00'};let iv,t0,left,last,trashMode=false,sel=null,tt,focusUiTimer;
const save=()=>localStorage.fw_prefs=JSON.stringify({minutes:S.m,focus:S.focus,keep:S.keep,nudge:S.n,reminder:S.rem,reviewTime:S.time}),get=()=>JSON.parse(localStorage.freewriting_entries||'[]'),put=v=>localStorage.freewriting_entries=JSON.stringify(v),getT=()=>JSON.parse(localStorage.freewriting_trash||'[]'),putT=v=>localStorage.freewriting_trash=JSON.stringify(v);
function toast(m='Copied'){let t=$('#toast');t.textContent=m;t.classList.add('on');clearTimeout(tt);tt=setTimeout(()=>t.classList.remove('on'),1200)}
async function cp(t){try{await navigator.clipboard.writeText(t)}catch{let x=document.createElement('textarea');x.value=t;document.body.appendChild(x);x.select();document.execCommand('copy');x.remove()}toast()}
function sh(t){navigator.share?navigator.share({text:t}).catch(()=>{}):cp(t)}
function focusChrome(revealed=false){clearTimeout(focusUiTimer);let w=$('#write');w.classList.remove('focus-clean');if(!S.focus||!w.classList.contains('on'))return;focusUiTimer=setTimeout(()=>w.classList.add('focus-clean'),revealed?2600:2200)}
function clearFocusChrome(){clearTimeout(focusUiTimer);$('#write').classList.remove('focus-clean')}
function show(id){$$('.scr').forEach(x=>x.classList.remove('on'));$('#'+id).classList.add('on');$('#bottom').style.display=(id==='write'||id==='writing')?'none':'grid';$$('.nav').forEach(x=>x.classList.toggle('on',id==='saved'?x.dataset.s==='home':x.dataset.s===id));if(id==='write')focusChrome();else clearFocusChrome();if(id==='library'){trashMode=false;render()}if(id==='writing')renderWriting()}
$('#write').addEventListener('pointerdown',()=>{if(S.focus)focusChrome(true)},{passive:true});
$$('.nav').forEach(x=>x.onclick=()=>show(x.dataset.s));
$$('.time').forEach(x=>x.onclick=()=>{if(x.dataset.m==='c'){let v=prompt('Minutes',S.m);if(!v)return;S.m=Math.max(1,Math.min(120,+v||3))}else S.m=+x.dataset.m;$$('.time').forEach(y=>y.classList.remove('on'));x.classList.add('on');save()});
$$('.sw[data-k]').forEach(x=>{let k=x.dataset.k;x.classList.toggle('off',!S[k]);x.onclick=()=>{S[k]=!S[k];x.classList.toggle('off',!S[k]);save()}});
$('#nv').textContent=S.n+'s';$('#minus').onclick=()=>{$('#nv').textContent=(S.n=Math.max(2,S.n-1))+'s';save()};$('#plus').onclick=()=>{$('#nv').textContent=(S.n=Math.min(30,S.n+1))+'s';save()};
const fmt=s=>String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')+':'+String(Math.max(0,s)%60).padStart(2,'0');
$('#start').onclick=()=>{left=S.m*60;t0=Date.now();$('#writer').value='';$('#timer').textContent=fmt(left);show('write');setTimeout(()=>$('#writer').focus(),50);clearInterval(iv);iv=setInterval(()=>{left--;$('#timer').textContent=left>0?fmt(left):(S.keep?'Keep going':'00:00');if(left<=0&&!S.keep)finish()},1000)};
$('#cancel').onclick=()=>{clearInterval(iv);show('home')};$('#finish').onclick=finish;
function finish(){clearInterval(iv);let t=$('#writer').value.trim();if(!t){show('home');return}let e={id:Date.now(),text:t,created:new Date().toISOString(),seconds:Math.max(1,Math.round((Date.now()-t0)/1000))},a=get();a.unshift(e);put(a);last=e;$('#excerpt').textContent=t;show('saved')}
$('#copySaved').onclick=()=>last&&cp(last.text);$('#shareSaved').onclick=()=>last&&sh(last.text);$('#doneSaved').onclick=()=>show('home');
const esc=s=>s.replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]));
function render(){let a=trashMode?getT():get();$('#atitle').textContent=trashMode?'Trash':'Archive';$('#count').textContent=trashMode?a.length:a.length+'/∞';$('#trash span').textContent=trashMode?'Archive':'Trash';$('#deleteAll').style.display=!trashMode&&a.length?'block':'none';$('#entries').innerHTML=a.length?a.map(e=>`<article class="entry" data-id="${e.id}"><div class="et">${esc(e.text)}</div><div class="meta">${new Date(e.created).toLocaleString('vi-VN')}</div></article>`).join(''):'<div class="empty">Nothing here yet.</div>';$$('.entry').forEach(el=>el.onclick=()=>{sel=+el.dataset.id;if(trashMode){let e=a.find(x=>x.id===sel);if(confirm('Restore this writing?')){putT(getT().filter(x=>x.id!==sel));let{trashedAt,...r}=e;put([r,...get()]);render()}}else show('writing')})}
$('#trash').onclick=()=>{trashMode=!trashMode;render()};$('#deleteAll').onclick=()=>{if(confirm('Move all writings to Trash?')){let a=get();putT(a.map(e=>({...e,trashedAt:new Date().toISOString()})).concat(getT()));put([]);render()}};
function cur(){return get().find(x=>x.id===sel)}
function saveInlineEdit(){let e=cur(),t=$('#writingText');if(!e||t.contentEditable!=='true')return;let text=t.innerText.trim(),a=get(),i=a.findIndex(x=>x.id===sel);if(text&&i>=0){a[i].text=text;put(a)}t.contentEditable='false';$('#writingEdit').classList.remove('editing');$('#writingEdit').setAttribute('aria-label','Edit')}
function renderWriting(){let e=cur();if(!e){show('library');return}let t=$('#writingText');t.contentEditable='false';t.textContent=e.text;$('#writingMeta').textContent=new Date(e.created).toLocaleString('vi-VN');$('#writingEdit').classList.remove('editing');$('#writingEdit').setAttribute('aria-label','Edit')}
$('#writingBack').onclick=()=>{saveInlineEdit();show('library')};
$('#writingEdit').onclick=()=>{let e=cur(),t=$('#writingText');if(!e)return;if(t.contentEditable==='true'){saveInlineEdit();toast('Saved')}else{t.contentEditable='true';$('#writingEdit').classList.add('editing');$('#writingEdit').setAttribute('aria-label','Finish editing');t.focus();let r=document.createRange();r.selectNodeContents(t);r.collapse(false);let s=window.getSelection();s.removeAllRanges();s.addRange(r)}};
$('#writingText').addEventListener('input',()=>{let e=cur();if(!e||$('#writingText').contentEditable!=='true')return;let a=get(),i=a.findIndex(x=>x.id===sel);if(i>=0){a[i].text=$('#writingText').innerText;put(a)}});
$('#writingCopy').onclick=()=>{saveInlineEdit();let e=cur();if(e)cp(e.text)};$('#writingShare').onclick=()=>{saveInlineEdit();let e=cur();if(e)sh(e.text)};
$('#writingTrash').onclick=()=>{let e=cur();if(e){put(get().filter(x=>x.id!==e.id));putT([{...e,trashedAt:new Date().toISOString()},...getT()]);sel=null;show('library');toast('Moved to Trash')}};
function open(id){$('#bottom').style.visibility='hidden';$('#scrim').classList.add('on');$('#'+id).classList.add('on')}
function close(){$('#scrim').classList.remove('on');$$('.sheet').forEach(x=>x.classList.remove('on'));$('#bottom').style.visibility='visible'}
$('#scrim').onclick=close;$$('[data-close]').forEach(x=>x.onclick=close);$('#bell').onclick=()=>open('reminder');

const PUSH_URL='https://cmejwdeklvmgqrollnqn.supabase.co/functions/v1/freewriting-reminder';
const VAPID_PUBLIC='BCKKFaDIFnaemf6SkcEkud7TdPyaAvqs9-gPKQ5S-kdC98ryzVqSTKmyFxE6MKy9mcGF7CUWJknLe1lS0Jm-hfQ';
const deviceId=()=>{let v=localStorage.fw_device_id;if(!v){v=crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.fw_device_id=v}return v};
const b64u=s=>{let p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),r=atob(b),a=new Uint8Array(r.length);for(let i=0;i<r.length;i++)a[i]=r.charCodeAt(i);return a};
async function regSW(){if(!('serviceWorker'in navigator))throw Error('Notifications are not supported on this device.');return navigator.serviceWorker.register('/sw.js?v=12.6.0')}
async function pushSub(create=true){let r=await regSW(),s=await r.pushManager.getSubscription();if(!s&&create)s=await r.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64u(VAPID_PUBLIC)});return s}
async function syncReminder(){let sub=await pushSub(true);let res=await fetch(PUSH_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'subscribe',deviceId:deviceId(),subscription:sub.toJSON(),enabled:true,reviewTime:S.time,utcOffsetMinutes:-new Date().getTimezoneOffset()})});if(!res.ok)throw Error('Could not save reminder.');return res.json()}
async function disableReminder(){try{await fetch(PUSH_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'disable',deviceId:deviceId()})})}catch{}}
async function initReminder(){if(!('Notification'in window)||!('serviceWorker'in navigator)||!('PushManager'in window)){S.rem=false;save();return}try{let sub=await pushSub(false);if(Notification.permission!=='granted'||!sub){S.rem=false;save()}}catch{S.rem=false;save()}$('#rs').classList.toggle('off',!S.rem)}
$('#rt').value=S.time;$('#rs').classList.toggle('off',!S.rem);
$('#rs').onclick=async()=>{if(!S.rem){try{if(!window.matchMedia('(display-mode: standalone)').matches&&!navigator.standalone)throw Error('Add Free Writing to Home Screen first.');let p=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(p!=='granted')throw Error('Notification permission was not granted.');await syncReminder();S.rem=true;$('#rs').classList.remove('off');save();toast('Reminder On')}catch(e){S.rem=false;$('#rs').classList.add('off');save();toast(e?.message||'Reminder unavailable')}}else{S.rem=false;$('#rs').classList.add('off');save();await disableReminder();toast('Reminder Off')}};
$('#rt').onchange=async e=>{S.time=e.target.value;save();if(S.rem){try{await syncReminder();toast('Time Saved')}catch{toast('Could not update reminder')}}};
initReminder();

function theme(d){document.body.classList.toggle('dark',d);localStorage.fw_dark=d?'1':'0';$('#tc').content=d?'#000000':'#fbfbfa';document.documentElement.style.background=d?'#000000':'#fbfbfa'}$('#theme').onclick=()=>theme(!document.body.classList.contains('dark'));theme(localStorage.fw_dark==='1');
